Tweets/config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  resources 'tweets'
end

Tweets/app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :message, presence:true
  validates :message, length:{in: 1..139}
end

Tweets/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Tweets/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(message: params[:tweet][:message],tdate: Time.current)
    if @tweet.save
      flash[:notice] = '1レコード追加しました。'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to root_path
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(message: params[:tweet][:message])
    redirect_to root_path
  end
end

Tweets/app/helpers/application_helper.rb
module ApplicationHelper
end

Tweets/app/helpers/tweets_helper.rb
module TweetsHelper
end

Tweets/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<body>
 <div id ="container">
   <div style="width:1000px;">
   <div id="header">
     <%= render "header" %>
   </div>
   <div id="sidebar">
     <%= render "sidebar" %>
   </div>
   <div id="content">
     <%= yield %>
   </div>
   <div id="footer">
     <%= render "footer"%>
   </div>
   </div>
 </div>
 <img class="soutai" height="200" src="/icon.jpg" width="200" />
</body>
</html>

Tweets/app/views/tweets/_form.html.erb
 <%= f.label :message,'メッセージ' %>
 <p><%= f.text_area :message, rows: 5, cols: 80 %></p>
 <p><%= f.submit 'ツイート' %></p>

Tweets/app/views/tweets/_header.html.erb
<img alt="head" height="200" src="/head.jpg" width="900" />
<hr>
<span id="m1">ツイート フォロー フォロワー いいね</span>
<hr>

Tweets/app/views/tweets/_sidebar.html.erb
<h1>近畿大学</h1>
<span id="abc">@kinkidaigakuPR</span>
<br>
近畿大学総務部広報室のTwitter公式アカウントです。近畿大学ホームページの更新情報を中心に、
大学に関する情報を発信していきます。個別DMでのお問い合わせには返信を行っておりませんので、
ご了承ください。
<br>
<br>
<img class="con" alt="head" src="/gps.JPG" align="left"/>
<div id="abc">大阪府大阪市</div>
<img class="con" alt="head" src="/rink.JPG" align="left"/>
<a href="instagram.com/kinkidaigakupr/">instagram.com/kinkidaigakupr/</a>
<br>
<img class="con" alt="head" src="/car.JPG" align="left"/>
<div id="abc">2010年12月に登録</div>
<%= link_to "ツイート", new_tweet_path %>

Tweets/app/views/tweets/edit.html.erb
<%= form_for @tweet , url:{action: :update} do |f| %>
 <%= render "form", f: f %>
<% end %>

Tweets/app/views/tweets/index.html.erb
  <div id="content">
   <% flash.each do |type,msg| %>
   <%= msg %>
   <% end %>

   <p>

<% @tweets.reverse_each do |tweet| %>

 <img class="icon" alt="head" src="/icon.jpg" align="left"/>
 <b>近畿大学</b> <span id="abc">@kinkidaigakuPR</span>　<%= (Time.current - tweet.tdate).to_i / 60 %> 分前
 <br>
 <%= link_to tweet.message %>
 <%= link_to '削除', tweet, method: :delete %>
 <%= link_to '表示', tweet %>
 <%= link_to '編集', edit_tweet_path(tweet) %>
 </p>
<% end %>

</div>

Tweets/app/views/tweets/new.html.erb
<% if @tweet.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
  <% @tweet.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @tweet , url:{action: :create} do |f| %>
 <%= render "form", f: f %>
<% end %>

Tweets/app/views/tweets/show.html.erb
<p>
  <strong>メッセージ:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>日付:</strong>
  <%= (Time.current - @tweet.tdate).to_i / 60 %>分前
</p>

<%= link_to '戻る','/' %>